### ISSUE TITLE
Saving the board layout

### ISSUE THREAD

**Issue by mdarocha** [jmaselbas/sref#1]
Hey, thanks for the program, it works great!

Is there any functionality for saving the images size and position? If not, can you guide me into how to implement such a functionality?

**Comment by jmaselbas** [comment]
Thanks,
There is currently no functionality for saving the images size/positions.
I think the best way (keeping things simple at first) would be to accept position and scale options from the command line.
and then keep track of image file names, and saving would be to print a valid command line to stdout.

**Comment by jmaselbas** [comment]
I've hacked an initial support for saving the image list with their absolute position in the "canvas", this does not save the images sizes.
I think I am going to scratch this and do another way: supporting reading an image list (with position and scale) from a text file. Then it will be possible to save everything in a script (with `#!/bin/sref`) to reopen the same images and layout.

**Comment by jmaselbas** [comment]
Hey, you can check the latest version, see commit fff44a8a93e97207ffd961db3cf82398df80e413
The option name might change but for now it's `-f file` and you can save the layout by pressing the key `S`.
I will add a way to configure keys latter.

**Comment by mdarocha** [comment]
latest build errors out:

```
sref.c: In function 'mod_match':
sref.c:50:56: error: 'ignoremod' undeclared (first use in this function)
   50 |         return mask == XK_ANY_MOD || mask == (state & ~ignoremod);
      |                                                        ^~~~~~~~~
sref.c:50:56: note: each undeclared identifier is reported only once for each function it appears in
sref.c: In function 'xev_keypress':
sref.c:844:29: error: 'shortcuts' undeclared (first use in this function); did you mean 'shortcut'?
  844 |         for (i = 0; i < LEN(shortcuts); i++) {
      |                             ^~~~~~~~~
sref.c:53:24: note: in definition of macro 'LEN'
   53 | #define LEN(a) (sizeof(a)/sizeof(*a))
      |                        ^
sref.c:846:32: warning: 'return' with a value, in function returning void [-Wreturn-type]
  846 |                         return shortcuts[i].func();
      |                                ^~~~~~~~~
sref.c:837:1: note: declared here
  837 | xev_keypress(XEvent *ev)
      | ^~~~~~~~~~~~
At top level:
sref.c:758:1: warning: 'saveboard' defined but not used [-Wunused-function]
  758 | saveboard(void)
      | ^~~~~~~~~
sref.c:752:1: warning: 'zoomreset' defined but not used [-Wunused-function]
  752 | zoomreset(void)
      | ^~~~~~~~~
make: *** [<builtin>: sref.o] Error 1
```

**Comment by mdarocha** [comment]
But the commit you reference builds and works fine, I'm closing this issue since its all I need for my workflow. Thank you very much!

**Comment by jmaselbas** [comment]
I must have a forgotten to add a local modification, I will fix this later today.
Keep in mind that I will eventually modify image coordinate system, this will break existing layouts.
But I do not know when I am going to make this modification.
